title = "R-Ladies organizational guidance"
baseURL = "https://guide.rladies.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']
enableGitInfo = true

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


[params]
  editURL = "https://github.com/rladies/rladiesguide/edit/main/content/"
  githubsource = "https://github.com/rladies/rladiesguide/blob/main/content/"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  #themeVariant = "rladies"

[params.author]
  name = "R-Ladies Global Team"


[Languages]
[Languages.en]
title = "R-Ladies organizational guidance"
weight = 1
languageName = "English"

[Languages.es]
title = "Guía de la organización R-Ladies"
weight = 2
languageName = "Español"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/rladies/rladiesguide"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Acknowledgements"
url = "/acknowledgements"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/rladies/rladiesguide"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Gracias"
url = "https://guide.rladies.org/acknowledgements"
weight = 30

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true